### ISSUE TITLE
can't install ... react-scripts: command not found

### ISSUE THREAD

**Issue by arnoldbird** [contentacms/contenta_react#10]
When I run yarn build && yarn install I get...

`/bin/sh: react-scripts: command not found
error Command failed with exit code 127.`

**Comment by arnoldbird** [comment]
I found a thread that suggested running...

npm install
yarn build && yarn install

That did it!

**Comment by e0ipso** [comment]
Thanks for looping back on this.

**Comment by justafish** [comment]
@arnoldbird You need to run `yarn install` before running `yarn build`
