### ISSUE TITLE
TypeError: Cannot read property 'small' of undefined

### ISSUE THREAD

**Issue by spoetnik** [contentacms/contenta_react#5]
yarn run v0.24.5
$ NODE_ENV=production node -r dotenv/config -r babel-register -r ignore-styles index.js 
/Users/username/Projects/projectname/frontend/src/styles/components/breakpoints.js:10
  mediumAndUp: "only screen and (min-width : " + (undefined.small + 1) + "px)",

**Comment by arifkhn46** [comment]
I am also facing the same issue.

**Comment by justafish** [comment]
Thanks for the fix @arifkhn46 !
